lazyload warp-cli -- '. <(warp-cli generate-completions zsh)'
lazyload fuck -- '. <(thefuck --alias)'
lazyload fk -- '. <(thefuck --alias fk)'
lazyload z -- '. <(zoxide init zsh)'
# lazyload artisan -- '. $ZDOTDIR/artisan-completion.zsh'
lazyload sail  -- '. $ZDOTDIR/artisan-completion.zsh'
lazyload box -- '. $ZDOTDIR/box.zsh'
lazyload nvm -- '. ~/.nvm/init-nvm.sh'
lazyload yainli -- '. $ZDOTDIR/yay.zsh'
