import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[shell]
program = "/usr/bin/zsh"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = false

[window]
decorations = "None"
dynamic_title = false
# opacity = 0.7
opacity = 1

[window.padding]
x = 5
y = 0
